### ISSUE TITLE
Please support vader filetype

### ISSUE THREAD

**Issue by przepompownia** [iamcco/coc-vimlsp#11]
or make the set of supported filetypes configurable.

When I switched to manually configured vimls, I did not encountered any problem so far, using it with vader tests.

**Comment by iamcco** [comment]
add `vimlsp.filetypes: ["vim"]' option.

**Comment by przepompownia** [comment]
Thanks!

**Comment by przepompownia** [comment]
Please make a release too. It will be simpler to fetch it by CocUpdate than manual fetch and build.

**Comment by iamcco** [comment]
It had been published.

**Comment by przepompownia** [comment]
I see completed new item in config json :+1:
