### ISSUE TITLE
Need help in config

### ISSUE THREAD

**Issue by heubd** [iamcco/coc-vimlsp#15]
I don't know where do this question .
How I get 
"Hover document" : I don't know how config that.
"Document symbols": CocList symbols? because don't work - > Workspace symbols provider not found for current document
"Document highlight": How do you "select/auto" in the example hl and msgs?
And the last, how have info with colors? for example in Document highlight, the info about expansion hightlight 'wildignorecase', is the colorscheme(I have gruvbox and don't do that)?

Sorry for my english, I am not native speaker.

Thanks in advance.

**Comment by iamcco** [comment]
For hover checkout coc.nvim README

``` vim
" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```

For document symbol: `CocList outline`

> "Document highlight": How do you "select/auto" in the example hl and msgs?

 checkout https://github.com/neoclide/coc-highlight

> And the last, how have info with colors? for example in Document highlight, the info about expansion hightlight 'wildignorecase', is the colorscheme(I have gruvbox and don't do that)?

https://github.com/iamcco/coc-vimlsp#config

**Comment by heubd** [comment]
> For hover checkout coc.nvim README
> 
> ```viml
> " Use K to show documentation in preview window.
> nnoremap <silent> K :call <SID>show_documentation()<CR>
> 
> function! s:show_documentation()
>   if (index(['vim','help'], &filetype) >= 0)
>     execute 'h '.expand('<cword>')
>   else
>     call CocAction('doHover')
>   endif
> endfunction
> ```
I have this config, but it go to the help page, don't show a box over the file.

> 
> For document symbol: `CocList outline`

Great, I'm new to coc and I still don't understand all the functions that have.
> 
> > "Document highlight": How do you "select/auto" in the example hl and msgs?
> 
> checkout https://github.com/neoclide/coc-highlight

Thanks.
> 
> > And the last, how have info with colors? for example in Document highlight, the info about expansion hightlight 'wildignorecase', is the colorscheme(I have gruvbox and don't do that)?
> 
> https://github.com/iamcco/coc-vimlsp#config

My error, when I read, I understood something else

**Comment by bratekarate** [comment]
Any update on how we enable hover? Is it supported or not?

> I have this config, but it go to the help page, don't show a box over the file.

Exactly, that is not a hover config. I tried it without the if statement, always using `doHover` as I described here #4. Any help or information if it is even supported would be appreciated.
