### ISSUE TITLE
unexpected error while using in vim

### ISSUE THREAD

**Issue by GopherJ** [iamcco/coc-vimlsp#16]
K to show documentation of nvim stuff is fine in neovim, but it crashes in vim.

![image](https://user-images.githubusercontent.com/33961674/86543338-d5ca8e80-bf1d-11ea-88f4-0c673fd74055.png)

Can the error be better? Like not found or neovim only..

**Comment by iamcco** [comment]
It's not error of this extension.

**Comment by chemzqm** [comment]
It's expected behavior of vim's default `:h` command since that function exists only on neovim.
