### ISSUE TITLE
What is the relation of this project with vint

### ISSUE THREAD

**Issue by pvonmoradi** [iamcco/coc-vimlsp#22]
I've installed coc-vimlsp on my vim. It does autocomplete vimscript and show errors. I'm wondering if this project uses  [https://github.com/Vimjas/vint](https://github.com/Vimjas/vint) under the hood?  
Do I also need to install CocDiagnostic and setup vint there or is this plugin enough for everything?

**Comment by iamcco** [comment]
It's not  relative to vint. It only report errors emit with vim-vimlparser.
