### ISSUE TITLE
Crash while using the complement

### ISSUE THREAD

**Issue by 66RING** [iamcco/coc-vimlsp#24]
Crash(core dumped) while using the complement

OS: arch linux 5.9.8-arch1-1
vim-version: 
```
NVIM v0.5.0-677-g59712f6db
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

minimum vimrc:

```vim
set nocompatible
set runtimepath=$VIMRUNTIME

set runtimepath+=/home/ring/.config/nvim/dein/repos/github.com/neoclide/coc.nvim_release
```

write some vimscript as follow, press `<c-n>/<c-p>` to move aroud, and then crash:

```vim
" a.vim
echo func<completion and then crash>
```
![vim_lsp_bug](https://user-images.githubusercontent.com/49358576/99260299-29e36900-2856-11eb-8ecb-cbac4244dc52.png)

**Comment by iamcco** [comment]
it's issue of neovim or coc, update coc or neovim.

**Comment by 66RING** [comment]
Fixed in the latest neovim
