### ISSUE TITLE
Cannot read property 'getGlobalFunctions' of undefined

### ISSUE THREAD

**Issue by bryansammon** [iamcco/coc-vimlsp#3]
I am trying the new version and am getting this error:   Message: Request textDocument/definition failed with message: Cannot read property 'getGlobalFunctions' of undefined

on vim 8.1

Any idea why?

**Comment by iamcco** [comment]
please paste full error message.

**Comment by bryansammon** [comment]
[Error  - 10:15:55 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'getGlobalFunctions' of undefined
  Code: -32603

**Comment by iamcco** [comment]
fix, please update and have a try.

**Comment by bryansammon** [comment]
Thanks it works from a .vim file, but from my .vimrc file it does not seem to work. You have any idea why? Both are filetype vim.

Only message I get is: `[coc.nvim] Definition not found`

**Comment by iamcco** [comment]
Seems parse your vimrc fail. It can not parse vimfile which has python embed like https://github.com/junegunn/vim-plug/blob/master/plug.vim#L1373

**Comment by bryansammon** [comment]
Interesting, thanks so much for helping! Happy to have this coc.nvim extension
