### ISSUE TITLE
Go to defintion make some confusion.

### ISSUE THREAD

**Issue by gh-liu** [iamcco/coc-vimlsp#32]
I use one plugin, and I want to make some changes in it, so I download it at other place then code, when I want go to defintion of something, the list will have two items: one is downloaded place , the other is my plugin place. Is there any way to hidden the plugin place.?

Sorry for my English.

**Comment by iamcco** [comment]
set `vimlsp.indexes.runtimepath` to false.

**Comment by gh-liu** [comment]
Thx.
