### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by oblitum** [iamcco/coc-vimlsp#5]
First time this is happening, I think it's due to last changes. When I open my `.vimrc` now (around 2k lines) the node instance for vimlsp fully consumes one core and doesn't stop until I close neovim.

**Comment by iamcco** [comment]
I have add `vimlsp.indexes.gap` option default from 0 to 100 to slow down CPU usage, this will also slow down index speed. 

You can also change `vimlsp.indexes.count` to smaller, default is 3, this effect the count of files index at the same time. 

Finally, if you don't want to get completeItems from vim's runtimepath, you can set `vimlsp.indexes.runtimepath` to false, this will let the behaviour as before.

**Comment by oblitum** [comment]
Thanks, but even with new default I'm getting high CPU usage (I think there's some bug, because it takes 100% of one core). I'll see whether setting `vimlsp.indexes.runtimepath` to `false` fixes it.

**Comment by oblitum** [comment]
> I'll see whether setting vimlsp.indexes.runtimepath to false fixes it.

Sadly even this didn't fix the issue. I think there should be some loop bug.

**Comment by oblitum** [comment]
I think the issue should be on language server actually, not the plugin, since I've not seem any relevant commit lately except for language server upgrades.

**Comment by oblitum** [comment]
It takes around one minute after I open my `.vimrc` for it to start looping, it doesn't happen right after opening neovim. Then it never ceases to consume CPU.

**Comment by iamcco** [comment]
Can't reproduce. Change `vimlsp.indexes.count` to 1 and `vimlsp.indexes.gap` to 1000 to see what happend

**Comment by oblitum** [comment]
@iamcco this seems like it made the problem go away.

**Comment by oblitum** [comment]
if you want to try my `.vimrc` to check for the issue, [it's this one](https://gist.github.com/oblitum/fb854a48566d1c74d16b26c9110582f2). You have to run `:PlugInstall` to install the plugins.

**Comment by oblitum** [comment]
> @iamcco this seems like it made the problem go away.

I was wrong, it just happened while I was editing code. Just more difficult for it to happen now.

**Comment by iamcco** [comment]
I have change default count to 1. I can't do more because I can't reproduce.

Test with default options with my MacBook Pro (13-inch):

![2019-08-07 16-00-48 2019-08-07 16_08_01](https://user-images.githubusercontent.com/5492542/62606114-1268c100-b92e-11e9-91ee-46b00f803b9b.gif)

**Comment by oblitum** [comment]
I dunno how exactly to reproduce, it happens after a while while editing my `.vimrc`.

I'm on ArchLinux using NeoVim master.

![12:38:50_07-08-2019](https://user-images.githubusercontent.com/1269815/62636780-957b1e80-b910-11e9-8df2-13c8b35251a0.png)

**Comment by oblitum** [comment]
The picture shows it's the `scan.js` that's doing it.

**Comment by iamcco** [comment]
I catch the problem, it seems vimlparser get dead loop while parse https://github.com/vim-scripts/formatvim/blob/master/autoload/format.vim

I have create issue https://github.com/vim-jp/vim-vimlparser/issues/144

**Comment by oblitum** [comment]
Just to avoid any confusion, I use it from https://github.com/oblitum/formatvim, not vim-scripts.

**Comment by iamcco** [comment]
OK, I have update the url

**Comment by oblitum** [comment]
For what's worth, I remove that plugin and frawor from my plugin dir but it still gets in a dead loop, maybe there's another one that causes it.

Thanks for reporting the issue on  vimlparser.

**Comment by oblitum** [comment]
Removing https://github.com/echuraev/translate-shell.vim/blob/master/autoload/common/history.vim from my plugins I stopped having this issue. I think it's vim-vimlparser to blame, so feel free to close it here if you think that's OK.

**Comment by iamcco** [comment]
I have fix the problem.
