### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by rickywu** [iamcco/coc-vimlsp#7]
![image](https://user-images.githubusercontent.com/442398/65134092-54f5e100-da36-11e9-972a-5efd892de844.png)

I tested only install coc-vimlsp, after startup gvim on Windows 10, there are 3 node.exe process and with high CPU utilization, node v10.16.0

vimrc:
---
: set sw=5 ft=vim 

let mapleader = ","
set enc=utf-8
set fenc=utf-8
source $VIMRUNTIME/vimrc_example.vim
scriptencoding utf-8

call plug#begin("$VIM/bundle")
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

"Coc
let g:coc_extension_root=$VIM."/coc/extensions"

**Comment by iamcco** [comment]
Is high CPU usage all the time?

**Comment by rickywu** [comment]
Test about 10 minutes and still with high CPU utilization

**Comment by iamcco** [comment]
Cannot reproduce

**Comment by rickywu** [comment]
Cannot reproduced after update system to 18990
