### ISSUE TITLE
let=<< syntax support

### ISSUE THREAD

**Issue by matthsims** [iamcco/coc-vimlsp#8]
Vim 8.1.1354 introduced a new syntax for setting a variable to a list of strings, supported in the 5.0 nvim nightly build:
``` vim
						*:let=<<* *:let-heredoc*
						*E990* *E991* *E172* *E221*
:let {var-name} =<< [trim] {marker}
text...
text...
{marker}
```

For example
``` vim
let names =<< trim END
  aaa
  bbb
  ccc
END

echo names
```
`['aaa', 'bbb', 'ccc']`

Currently coc-vimlsp reports a syntax error.

**Comment by iamcco** [comment]
Refer https://github.com/vim-jp/vim-vimlparser/pull/120
